version: '3.5'

services:
  wclient:
    build:
      context: .
      dockerfile: wclient.Dockerfile
    command: wclient
    environment:
      - CLIENT_WHOST=wweb
    depends_on:
      - wweb

  wweb:
    build:
      context: .
      dockerfile: wweb.Dockerfile
    command: wweb
    ports:
      - 3000:3000
    environment:
      - WEB_INTERFACE=0.0.0.0
      - WEB_PORT=3000
      - DB_HOST=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=development
      - METRIC_HOST=graphite
      - METRIC_PORT=2003
      - SERVICE_NAME=wweb
    depends_on:
      - postgres
      - pgadmin4
      - graphite

  postgres:
    image: postgres:11.4
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=
      - TZ=GMT

  pgadmin4:
    image: dpage/pgadmin4
    ports:
      - 2999:80
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@onion"
      PGADMIN_DEFAULT_PASSWORD: "admin"

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 5050:3000
    volumes:
      - grafana-volume
    logging:
      driver: none

  graphite:
    image: graphiteapp/graphite-statsd
    container_name: graphite
    ports:
      - 2003:2003
    restart: always
    logging:
      driver: none

volumes:
  grafana-volume:
    external: true