version: '3.5'

services:
  wclient:
    build:
      context: .
      dockerfile: wclient.Dockerfile
    command: wclient
    environment:
      - CLIENT_WHOST=wweb
    depends_on:
      - wweb

  wweb:
    build:
      context: .
      dockerfile: wweb.Dockerfile
    command: wweb
    ports:
      - 3000:3000
    environment:
      - WEB_INTERFACE=0.0.0.0
      - WEB_PORT=3000
      - DB_HOST=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=development
    depends_on:
      - postgres
      - pgadmin4

  postgres:
    image: postgres:11.4
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=
      - TZ=GMT

  pgadmin4:
    image: dpage/pgadmin4
    ports:
      - 2999:80
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@onion"
      PGADMIN_DEFAULT_PASSWORD: "admin"