version: '3.5'

services:
  wclient:
    build:
      context: .
      dockerfile: wclient.Dockerfile
    command: wclient
    environment:
      - CLIENT_WHOST=wweb
      - SERVICE_GAME=wgame:3100

      - METRIC_HOST=graphite
      - METRIC_PORT=2003

      - SERVICE_NAME=wclient
    depends_on:
      - wweb

  wweb:
    build:
      context: .
      dockerfile: wweb.Dockerfile
    command: wweb
    ports:
      - 3000:3000
    environment:
      - WEB_INTERFACE=0.0.0.0
      - WEB_PORT=3000
      - DB_HOST=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=development
      - DB_PORT=5432
      - METRIC_HOST=graphite
      - METRIC_PORT=2003

      - SERVICE_NAME=wweb
    depends_on:
      - postgres
      - graphite
      - wauth

  wgame:
    build:
      context: .
      dockerfile: wgame.Dockerfile
    command: wgame
    ports:
      - 3100:3100
    environment:
      - RPC_INTERFACE=0.0.0.0
      - RPC_PORT=3100
      - DB_HOST=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=development
      - METRIC_HOST=graphite
      - METRIC_PORT=2003

      - SERVICE_NAME=wgame

      - SERVICE_AUTH=wauth:3101
    depends_on:
      - postgres
      - graphite
      - wauth

  wauth:
    build:
      context: .
      dockerfile: wauth.Dockerfile
    command: wauth
    ports:
      - 3101:3101
    environment:
      - RPC_INTERFACE=0.0.0.0
      - RPC_PORT=3101
      - DB_HOST=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=development
      - DB_PORT=5432
      - ME_HOST=redis
      - ME_PORT=6379
      - ME_PASSWORD=nopasswd
      - METRIC_HOST=graphite
      - METRIC_PORT=2003

      - SERVICE_NAME=wauth
    depends_on:
      - postgres
      - graphite
      - redis

  pgadmin4:
    image: dpage/pgadmin4:4.11
    container_name: pgadmin4
    ports:
      - 3200:80
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@onion"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    logging:
      driver: none
    depends_on:
      - postgres

  grafana:
    image: grafana/grafana:6.2.5
    container_name: grafana
    ports:
      - 3201:3000
    volumes:
      - grafana-volume
    logging:
      driver: none
    depends_on:
      - graphite

  graphite:
    image: graphiteapp/graphite-statsd:1.1.5-12
    container_name: graphite
    ports:
      - 2003:2003
      - 8080:8080
    restart: always
    logging:
      driver: none

  postgres:
    image: postgres:11.4
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=
      - TZ=GMT
    logging:
      driver: none

  redis:
    image: redis:5.0.5
    container_name: redis
    command: redis-server --requirepass nopasswd
    ports:
      - 6379:6379

volumes:
  grafana-volume:
    external: true