version: '3.5'

services:
  postgres:
    image: postgres:11.4
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=
      - TZ=GMT

  redis:
    image: redis:5.0.5
    container_name: redis
    command: redis-server --requirepass nopasswd
