{
 "title": "Docker Metrics",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Memory %",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "target": "metrics.*.mem_perc" }
   ]
  },
  {
   "title": "CPU %",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "target": "metrics.*.cpu_perc" }
   ]
  },
  {
   "title": "PIDS",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "metrics.*.pids" }
   ]
  },
  {
   "title": "Block I/O",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "decbits" }
   ],
   "targets": [
    { "target": "metrics.*.block_in" },
    { "target": "metrics.*.block_out" }
   ]
  },
  {
   "title": "Net Output",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "decbits" }
   ],
   "targets": [
    { "target": "metrics.*.net_out" }
   ]
  },
  {
   "title": "Net Input",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "decbits" }
   ],
   "targets": [
    { "target": "metrics.*.net_in" }
   ]
  }
 ]
}