{
 "title": "Rudy Arch",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Characters",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "worlds.*.characters" }
   ]
  },
  {
   "title": "RClient",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "bench.rclient.*.*" }
   ]
  },
  {
   "title": "RWeb",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "bench.rweb.routes.*.*" }
   ]
  }
 ]
}